# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name MorganFPS
#' @title Morgan fingerprints collection
#' @description Efficient structure for storing a set of Morgan fingerprints
#' @field new Constructor. Accepts either a vector of fingerprints in hexadecimal
#'   format or a path to a binary file of fingerprints using the argument
#'   `from_file = TRUE`. The vector of fingerprints can optionally be named.
#'   Names need to be coercible to integers. When querying, the indices i and j
#'   refer to the given names.
#' @field tanimoto (i,j) similarity between fingerprints i and j
#' @field tanimoto_all (i) similarity between fingerprint i and all others
#' @field tanimoto_threshold (threshold) similarity of all NxN combinations of fingerprints above the set threshold
#' @field tanimoto_subset (i,j) similarity of a set of fingerprints against another set, or all other fingerprints in the collection when j is NULL
#' @field tanimoto_ext (s) similarity between external hexadecimal string s and all
#'    fingerprints in the collection
#' @field save_file (path, compression_level) Save fingerprints to file in binary format
#' @field size number of bytes used to store the fingerprints
#' @importFrom Rcpp cpp_object_initializer
#' @export
NULL

#' Tanimoto similarity between two Morgan fingerprints
#'
#' Computes Tanimoto similarity between two hexadecimal strings
#'
#' @param s1 Hexadecimal string of length 512
#' @param s2 Hexadecimal string of length 512
#' @return Jaccard similarity over the bits representing individual keys
#' @export
tanimoto <- function(s1, s2) {
    .Call('_morgancpp_tanimoto', PACKAGE = 'morgancpp', s1, s2)
}

